# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"explore_df": "00_core.ipynb",
         "format_features": "00_core.ipynb",
         "detect_features": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://xanderhorn, ryanfras.github.io/mldato/"

git_url = "https://github.com/xanderhorn, ryanfras/mldato/tree/master/"

def custom_doc_links(name): return None
